spring.application.name=ChatBot
spring.application.version=0.0.1-SNAPSHOT

#logging
logging.level.open.source.ai.chatbot=

#API Details
chatbot.api.key=
chatbot.api.url=

#Thread Pool Configuration
thread.min.pool.size=
thread.max.pool.size=
thread.queue.size=
thread.keep.alive.time=