spring.application.name=ChatBot
spring.application.version=0.0.1-SNAPSHOT

#logging
logging.level.open.source.ai.chatbot=${LOG_LEVEL}

#API Details
chatbot.api.key=${TOGETHER_AI_KEY}
chatbot.api.url=${TOGETHER_AI_URL}
chatbot.api.model=${TOGETHER_AI_MODEL}
